
### VS

POST https://localhost:7185/api/payment/create
Content-Type: application/json

{
    "amount": 86.10,
    "currency": "GBP"
}


### docker

POST https://localhost:4433/api/payment/create
Content-Type: application/json

{
    "amount": 86.10,
    "currency": "GBP"
}